# Generated by Django 3.2.3 on 2021-05-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('ratings', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('actor_name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
            ],
        ),
    ]
